In [1]:
import numpy as np

In [34]:
# create a 1D array of random numbers from 0 to 9
Y = np.random.randint(0, 5, 5)
# create a 2D random numbers 
Y_prid = np.random.randint(0, 10, (5, 5))
Y,Y_prid

(array([4, 2, 0, 1, 2]),
 array([[6, 7, 4, 7, 6],
        [3, 2, 4, 7, 8],
        [4, 6, 6, 6, 2],
        [6, 3, 0, 6, 3],
        [3, 1, 3, 0, 6]]))

In [38]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [35]:
# index the columns of Y_prid with the indicies of Y
Y_prid[Y, np.arange(5)]

array([3, 6, 4, 7, 2])